### ISSUE TITLE
Error trying to launch the driver using one of the provided launch files (WSL)

### ISSUE THREAD

**Issue by philianeles** [compas-rrc/compas_rrc_ros#5]
I am trying to follow the steps here: https://github.com/gramaziokohler/compas_rrc_ros#linux 

to launch the driver using one of the provided launch files and having this error:

> sercan@ITA-GRAM-W-60:~/catkin_ws_abb$ roslaunch compas_rrc_driver bringup.launch robot_ip:=127.0.0.1 robot_streaming_port:=30101 robot_state_port:=30201
> ... logging to /home/sercan/.ros/log/004eab7c-7b36-11ea-bc01-54e1ad9244b0/roslaunch-ITA-GRAM-W-60-1403.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://ITA-GRAM-W-60:51767/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /robot_ip_address: 127.0.0.1
>  * /robot_state_port: 30201
>  * /robot_streaming_port: 30101
>  * /rosdistro: melodic
>  * /rosversion: 1.14.3
>  * /sequence_check_mode: none
> 
> NODES
>   /
>     compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759 (compas_rrc_driver/driver.py)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759-1]: started with pid [1418]
> [DEBUG] [1586528255.257624]: init_node, name[/compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759], pid[1418]
> [DEBUG] [1586528255.260771]: binding to 0.0.0.0 0
> [DEBUG] [1586528255.266043]: bound to 0.0.0.0 51778
> [DEBUG] [1586528255.267449]: ... service URL is rosrpc://ITA-GRAM-W-60:51778
> [DEBUG] [1586528255.268431]: [/compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759/get_loggers]: new Service instance
> [DEBUG] [1586528255.271406]: ... service URL is rosrpc://ITA-GRAM-W-60:51778
> [DEBUG] [1586528255.272435]: [/compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759/set_logger_level]: new Service instance
> [INFO] [1586528255.277967]: Connecting robot 127.0.0.1 (ports 30101 & 30201, sequence check mode=none)
> [INFO] [1586528255.279274]: Streaming interface: Connecting socket 127.0.0.1:30101
> [ERROR] [1586528256.284022]: Cannot connect streaming interface: 127.0.0.1:30101
> [INFO] [1586528256.287338]: Disconnecting streaming interface...
> [INFO] [1586528256.289725]: Streaming interface: Disconnecting socket
> Traceback (most recent call last):
>   File "/home/sercan/catkin_ws_abb/src/compas_rrc_ros/src/compas_rrc_driver/driver.py", line 319, in <module>
>     main()
>   File "/home/sercan/catkin_ws_abb/src/compas_rrc_ros/src/compas_rrc_driver/driver.py", line 276, in main
>     streaming_interface.connect()
>   File "/home/sercan/catkin_ws_abb/src/compas_rrc_ros/src/compas_rrc_driver/driver.py", line 161, in connect
>     self._connect_socket()
>   File "/home/sercan/catkin_ws_abb/src/compas_rrc_ros/src/compas_rrc_driver/driver.py", line 187, in _connect_socket
>     self.socket = socket.create_connection((self.host, self.port), CONNECTION_TIMEOUT)
>   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
>     raise err
> socket.error: [Errno 111] Connection refused
> [compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759-1] process has died [pid 1418, exit code 1, cmd /home/sercan/catkin_ws_abb/src/compas_rrc_ros/src/compas_rrc_driver/driver.py __name:=compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759 __log:=/home/sercan/.ros/log/004eab7c-7b36-11ea-bc01-54e1ad9244b0/compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759-1.log].
> log file: /home/sercan/.ros/log/004eab7c-7b36-11ea-bc01-54e1ad9244b0/compas_rrc_driver_ITA_GRAM_W_60_1403_4890098548518323759-1*.log

any hints how to avoid this?

**Comment by gonzalocasas** [comment]
Closing this for the time being, but if you still face issues, please re-open!
