### ISSUE TITLE
Latest tag on DockerHub not pointing to latest image based on git tag

### ISSUE THREAD

**Issue by tetov** [compas-rrc/compas_rrc_ros#8]
Probable cause is [GitHub workflow](https://github.com/compas-rrc/compas_rrc_ros/blob/main/.github/workflows/build-image.yml)

![image](https://github.com/compas-rrc/compas_rrc_ros/assets/14882117/3efb4fe0-3203-4691-a666-70ddfb8e4344)

See #support on Slack for more context.

**Comment by tetov** [comment]
I'll look into this later today.

**Comment by tetov** [comment]
@gonzalocasas: There's some trouble with rosdep not resolving python2- prefixed packages. My quickfix were to switch to python3 which works. However there's a conflict between catkin and python{2,3}-catkin-pkg which can be resolved by instead depend on python-catkin-pkg-modules. See https://github.com/ros/catkin/issues/991.

I'm not explaining it fully because I mainly want to ask if you think we need python{2,3}-catkin-pkg as a `buildtool_depend`? It builds for kinetic without it (in docker container). I'll test on more distros.

I'll investigate more..

**Comment by fleischp** [comment]
@tetov : hi Anton thanks for your help! I think Gonzalo will help here as soon he is free for the task. Best Philippe

**Comment by tetov** [comment]
@fleischp: Hi! Hope you are well! Yeah, I'm not in a rush. There's no problem really as long as we use v1.1.2 instead of latest in our docker-compose files, but this investigation makes me think that we should update our docker images to ROS 1 Noetic instead of ROS 1 Kinetic since Kinectic has reached end of life.

I'll keep digging :).

**Comment by gonzalocasas** [comment]
Yes. Actually, i mostly use [this image](https://github.com/gramaziokohler/ros_docker/tree/master/ros-noetic-dfab) instead.

**Comment by tetov** [comment]
Ok. So in that case we could consider compas_rrc_ros tested on noetic. Would you be OK with me sending one two PRs with updated CI and update to Noetic in this repo?

**Comment by tetov** [comment]
It might be a good time to make a release since the container is now built with noetic. This would also fix this issue ;).

**Comment by gonzalocasas** [comment]
[Version 1.1.3](https://github.com/compas-rrc/compas_rrc_ros/actions/runs/6138900216) is being built as we speak :)  After that, we can close this issue, right?

**Comment by gonzalocasas** [comment]
New images published!

**Comment by tetov** [comment]
Great! Thanks!
